config/routes.rb
Rails.application.routes.draw do
  root "statics#welcome"
  get "/help", to: "statics#help"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error-explanation" class="error-explanation">
    <div class="alert alert-danger">
      <%= t ".form_contain" %> <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if feeds_for(current_user).any? %>
  <ol class="posts">
    <%= render feeds_for(current_user) %>
  </ol>
  <%= paginate feeds_for(current_user), theme: "twitter-bootstrap-3" %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for @post do |f| %>
  <%= render "shared/errors", object: f.object %>

  <%= f.label :title, t(".title") %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :content, t(".content") %>
  <%= f.text_area :content, placeholder: t(".compose"), class: "form-control" %>

  <%= f.submit t(".post"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<%= link_to following_user_path @user do %>
  <strong class="stat following">
    <%= @user.following.size %>
  </strong>
  <%= t ".following" %>
<% end %>
<%= link_to followers_user_path @user do %>
  <strong class="stat followers">
    <%= @user.followers.size %>
  </strong>
  <%= t ".followers" %>
<% end %>

app/views/shared/_user_info.html.erb
<h3>
  <%= image_tag "avatar.png", alt: user.user_name, class: "avatar" %>
  <ul class="user-view">
    <li><%= user.full_name %></li>
    <li><span><%= link_to t(".view_profile"), user %></span></li>
    <li><span><%= pluralize user.posts.count, t(".post") %></span></li>
  </ul>
</h3>