config/routes.rb
Rails.application.routes.draw do
  root "statics#welcome"
  get "/help", to: "statics#help"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def welcome
    @post = current_user.posts.build if logged_in?
  end

  def help
  end
end

app/views/statics/help.html.erb
<% provide :title, t(".help") %>
<div class="center">
  <h1><%= t ".help" %></h1>
  <h3><%= t ".support" %></h3>
</div>

app/views/statics/welcome.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user-info">
        <%= render "shared/user_info", user: current_user %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
      <section class="post_form">
        <%= render "shared/post_form" %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= t ".post_feed" %></h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
  <div class="center">
    <h1><%= t ".welcome_tip" %></h1>
    <h4><%= t ".description" %></h4>
    <ul class="action">
      <li><%= link_to t(".signup"), signup_path, class: "btn btn-lg btn-primary" %></li>
      <li><h4><%= t ".or" %></h4></li>
      <li><%= link_to t(".login"), login_path, class: "btn btn-lg btn-success" %></li>
    </ul>
  </div>
<% end %>