config/routes.rb
Rails.application.routes.draw do
  root "statics#welcome"
  get "/help", to: "statics#help"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_default.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
<%= favicon_link_tag "sl-icon.png" %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <span class="version"><%= t(".version", year: Time.now.year) %></span>
  <%= button_tag t(".top"), type: "button", class: "to-top", id: "to-top" %>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top header">
  <%= form_tag users_url, method: :get, class: "navbar-form navbar-left search-form" do %>
    <%= link_to image_tag("sl-icon.png", alt: t(".logo"), class: "logo"),
      root_path %>
    <%= text_field_tag :search, params[:search], placeholder: t(".placeholder"),
      class: "form-control search-box" %>
  <% end %>
  <ul class="navbar navbar-nav navbar-right link-bar">
    <% if logged_in? %>
      <li><%= link_to t(".profile"), current_user %></li>
      <li><%= link_to t(".home"), root_path %></li>
      <li><%= link_to t(".help"), help_path %></li>
      <li class="dropdown">
        <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
          <b class="caret"></b>
        <% end %>
        <ul class="dropdown-menu">
          <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
          <li><%= link_to t(".logout"), logout_path, method: :delete %></li>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title_for yield :title %></title>
    <%= render "layouts/default" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>